export const UNASSIGNED = 'UNASSIGNED';
export const UNASSIGNED_SUCCESS = 'UNASSIGNED_SUCCESS';
export const UNASSIGNED_FAIL = 'UNASSIGNED_FAIL';
export const INTEREST = 'INTEREST';
export const INTEREST_SUCCESS = 'INTEREST_SUCCESS';
export const RESET = 'RESET';
export const EMAIL = 'EMAIL';